global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "policy-pass-api"
    metrics_path: /metrics
    scrape_interval: 30s
    static_configs:
      - targets: ["54.116.152.245:8080"]
        labels:
          instance: "policy-pass-api"

  - job_name: "node-exporter"
    static_configs:
      - targets: ["node-exporter:9100"]
        labels:
          instance: "policy-pass-monitor"
      - targets: ["54.116.152.245:9100"]
        labels:
          instance: "policy-pass-api"

  # GCP MongoDB Exporter (enable when GCP exporter is exposed externally)
  # - job_name: "mongodb"
  #   static_configs:
  #     - targets: ["<GCP_MONGO_VM_EXTERNAL_IP>:9216"]
  #       labels:
  #         instance: "rag-mongo-vm"

  # GCP Node Exporter - Airflow VM (enable when exposed externally)
  # - job_name: "node-airflow-vm"
  #   static_configs:
  #     - targets: ["<GCP_AIRFLOW_VM_EXTERNAL_IP>:9100"]
  #       labels:
  #         instance: "rag-airflow-vm"
